name: Publish Docker image

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: submarinonline/misskey
  NOTIFY_MSG: |
    New release pushed! \
    https://github.com/Submarinonline/misskey

jobs:
  push_to_registry:
    name: Push Docker image to ghcr
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log in to ghcr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to ghcr
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notify
        run: |
          curl -fsSL -XPOST \
            -d"{\"i\":\"${{ secrets.MISSKEY_TOKEN }}\",\"text\":\"${{ env.NOTIFY_MSG }}\"}" \
            ${{ secrets.MISSKEY_HOST }}/api/notes/create
